my_string = input("Введите текст: ")
print("Число введённых символов:",my_string.__len__())
print("В верхнем регистре этот текст выглядит так:",my_string.upper())
print("А в нижнем регистре он выглядит так:", my_string.lower())
print("Ваш текст без пробелов:", my_string.replace(" ",""))
print("Первый символ введённого текста:", my_string[0])
print("Последний символ введённого текста:", my_string[-1])
